#!/bin/bash

# usage: ./export [site|ehsop|blog]
# usage: ./export [site|ehsop|blog] [master|dev] [new]

# Первый параметр указывает тип сборки: 
#   site - сайт визитка,
#   eshop - интернет магазин
#   blog - социальный блог

# Второй параметр указывает на репо:
#   master - стабильная версия
#   dev - в разработке

DEFMODS="bos tinymce uprofile widget news sitemap filemanager notify rss"

if [ $1 == "eshop" ]
then
    DISTR="eshop"
    MODS="$DEFMODS catalog eshop"
fi

if [ $1 == "blog" ]
then
    DISTR="blog"
    MODS="$DEFMODS blog comment socialist urating"
else
    DISTR="site"
    MODS=$DEFMODS
fi

if [ $2 == "dev" ]
then
    DISTR="$DISTR-dev"
    REPO="dev"
else
    REPO="master"
fi

DIR="build/$DISTR"

mkdir -p $DIR
git clone -b $REPO https://github.com/abricos/abricos-core.git $DIR

cd $DIR

rm -fr .git
rm -fr .gitignore
rm -fr cache/.gitignore
rm -fr images/.gitignore
rm -fr includes/.gitignore
rm -fr js/.gitignore
rm -fr modules/.gitignore
rm -fr tt/.gitignore
rm -fr .gitmodules

if [ $3 == "new" ]
then
    cp def.htaccess .htaccess
    cp includes/config.example.php includes/config.php
fi

for n in $MODS; do
    echo "Export abriocs module $n"
    git clone -b $REPO https://github.com/abricos/abricos-mod-$n.git modules/$n
    rm -fr modules/$n/.git
    rm -fr modules/$n/.gitignore
done
