#!/bin/bash

# usage: ./export [site|ehsop]
# usage: ./export [site|ehsop] [master|dev]

# Первый параметр указывает тип сборки: 
#   site - сайт визитка,
#   eshop - интернет магазин

# Второй параметр указывает на репо:
#   master - стабильная версия
#   dev - в разработке

DEFMODS="bos tinymce uprofile widget news sitemap filemanager notify"

if [ $1 == "eshop" ] 
then
    DISTR="eshop"
    MODS="$DEFMODS catalog eshop"
else
    DISTR="site"
    MODS=$DEFMODS
fi

if [ $2 == "dev" ]
then
    REPO="dev"
else
    REPO="master"
fi

DIR="build/$DISTR"

mkdir -p $DIR
git clone -b $REPO git@github.com:abricos/abricos-core.git $DIR

cd $DIR

rm -fr .git
rm -fr .gitignore
rm -fr cache/.gitignore
rm -fr images/.gitignore
rm -fr includes/.gitignore
rm -fr js/.gitignore
rm -fr modules/.gitignore
rm -fr tt/.gitignore
rm -fr .gitmodules
cp def.htaccess .htaccess
cp includes/config.example.php includes/config.php


for n in $MODS; do
    echo "Export abriocs module $n"
    git clone -b $REPO git@github.com:abricos/abricos-mod-$n.git modules/$n
    rm -fr modules/$n/.git
    rm -fr modules/$n/.gitignore
done

